### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Stelian2022** [cefomk/ceppic_dwwm_foad_07_03_2023#1]
Bonjour Mehdi , j'ai fait des modif dans l'apres midi et je comprend pas pq ca m'affiche quelques erreurs .Je n'arrive pas a voir pourquoi ça ne marche pas .Y'as 2 heures tout marché tres bien . T'as une idée d'ou ça viens ?
Merci
![Capture d'écran 2023-03-07 145057](https://user-images.githubusercontent.com/116893573/223445564-82ed726f-8b43-45c5-ba43-9aabdae441fd.png)

**Comment by cefomk** [comment]
Debug ta variable $pseudo à savoir si elle est vide ?
Car le message d'erreur , que tu entre quelque chose dans une colonne d'une table qui ne peut etre null.

**Comment by Stelian2022** [comment]
je viens de faire dbug sur $pseudo , ça affiche NULL du coup

**Comment by cefomk** [comment]
Donc l'erreur est correcte,
comme je n'ai pas precisé quels sont obligatoires, et qu'on se connecte par email,
tu peux mettre le login dans ta table a NULL par default comme cela tu aura aucun probleme si tu renseigne un login vide.
D'ou l'interet de savoir ce qu'on rentre dans notre base et si les champs doivent null ou pas par default.

**Comment by Stelian2022** [comment]
ah oui effectivement , j'ai compris . Merci beaucoup
